# SPDX-FileCopyrightText: 2023-2025 The ReReSo Authors, see AUTHORS.md
#
# SPDX-License-Identifier: Apache-2.0

[project]
name = "dumux-benchmark-packager"
version = "1"
requires-python = ">=3.13"
dependencies = [
    "cmakelang>=0.6.13",
]
