# SPDX-FileCopyrightText: 2023-2025 The ReReSo Authors, see AUTHORS.md
#
# SPDX-License-Identifier: Apache-2.0

name: Build

env:
  DEBIAN_FRONTEND: noninteractive
  SINGULARITY_OPTS: --fakeroot
  SINGULARITY_VERSION: 4.3.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: sudo apt-get install fakeroot
      - run: wget https://github.com/sylabs/singularity/releases/download/v$SINGULARITY_VERSION/singularity-ce_$SINGULARITY_VERSION-$(lsb_release -cs)_amd64.deb
      - run: sudo dpkg -i singularity-ce_$SINGULARITY_VERSION-$(lsb_release -cs)_amd64.deb || true
      - run: sudo apt-get install -fy

      - uses: astral-sh/setup-uv@v5

      - run: make -j $(nproc)
      - run: sed '/^#/,$!d' README.Zenodo.md > README.md
      - uses: actions/upload-artifact@v4
        with:
          name: zenodo-package
          path: |
            case-studies.zip
            README.md
